import { type ClassValue, clsx } from "clsx"
import { twMerge } from "tailwind-merge"

// This function is from shadcn/ui (auto-generated by `npx shadcn-ui@latest init`)
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

// Custom utility functions below this line
export function generateUserId(): string {
  if (typeof window === 'undefined') return 'server_user';
  
  const stored = localStorage.getItem('quickpoll_user_id');
  if (stored) return stored;
  
  const newId = `user_${Math.random().toString(36).substr(2, 9)}`;
  localStorage.setItem('quickpoll_user_id', newId);
  return newId;
}

export function formatDate(date: string | Date): string {
  const d = new Date(date);
  const now = new Date();
  const diff = now.getTime() - d.getTime();
  
  const seconds = Math.floor(diff / 1000);
  const minutes = Math.floor(seconds / 60);
  const hours = Math.floor(minutes / 60);
  const days = Math.floor(hours / 24);
  
  if (seconds < 60) return 'just now';
  if (minutes < 60) return `${minutes}m ago`;
  if (hours < 24) return `${hours}h ago`;
  if (days < 7) return `${days}d ago`;
  
  return d.toLocaleDateString();
}

export function calculatePercentage(votes: number, total: number): number {
  if (total === 0) return 0;
  return Math.round((votes / total) * 100);
}
